// This file was generated by Prisma, and assumes you have installed the following:
// O prisma.config.ts, no Prisma 7 passou a ser criado pelo prisma init e é usado para configurar o CLI e a conexão do banco.
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
